### ISSUE TITLE
Use tour.next() in react-shepherd

### ISSUE THREAD

**Issue by Baspa** [shipshapecode/react-shepherd#151]
If I use the React wrapper for Shepherd.js how can I advance to the next step? Where can I find the tour instance?

**Comment by rwwagner90** [comment]
@Baspa have you tried what the usage suggests? https://github.com/shipshapecode/react-shepherd#usage

**Comment by rwwagner90** [comment]
@chuckcarpenter perhaps you could help with this question?

**Comment by Baspa** [comment]
> @Baspa have you tried what the usage suggests? https://github.com/shipshapecode/react-shepherd#usage

Yes I did @chuckcarpenter

**Comment by chuckcarpenter** [comment]
@Baspa this should be like how the tour context is passed here: https://github.com/shipshapecode/react-shepherd/blob/master/example/src/App.js#L25

And given that reference, you should be able to use any method on the instance. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/706378/70362410-207a1000-1842-11ea-8bc3-a586fc900fea.png">

**Comment by chuckcarpenter** [comment]
Closing on last answer.
