### ISSUE TITLE
showCancelLink not working

### ISSUE THREAD

**Issue by realRaghavGupta** [shipshapecode/react-shepherd#162]
I tried showCancelLink: true in the defaultStepOptions as given in the example, but its not working. Tried adding to the individual steps, its still not working.

**Comment by rwwagner90** [comment]
@realRaghavGupta can you please show us the code that is not working? @chuckcarpenter does the cancel link show up for you?

**Comment by realRaghavGupta** [comment]
const tourOptions = {
	defaultStepOptions: { scrollTo:true, cancelIcon:true },
	useModalOverlay: true
  };

I am using this.

Cancel link doesn't show up for me.

**Comment by rwwagner90** [comment]
@realRaghavGupta I think `cancelIcon` is supposed to be an object. Check the format here https://shepherdjs.dev/docs/Step.html#Step

**Comment by chuckcarpenter** [comment]
@realRaghavGupta you're right the example does have the old way. Using this does work:

```
const tourOptions = {
  defaultStepOptions: {
    cancelIcon: {
      enabled: true
    }
  },
  useModalOverlay: true
};
```

<img width="682" alt="image" src="https://user-images.githubusercontent.com/706378/71055258-2ad5bd00-2112-11ea-806f-86039e9beee9.png">

I'm going to PR an update to the example site and readme. Thanks for pointing it out!
