### ISSUE TITLE
Published code isnt the same as whats on the repo.

### ISSUE THREAD

**Issue by williejay2017** [shipshapecode/react-shepherd#2]
I installed this via yarn into a project and couldn't import ShepherdTour or TourMethods. Did a little digging around and it looks like you are referencing a deprecated dependency in your package.json (tether-shepherd vs shepherd) on the published code. The index.js from the published code is different from whats installed via package manager. There is no modules (ShepherdTour or TourMethods) to refer to in the published code. 

Thanks

**Comment by chuckcarpenter** [comment]
Correct, I haven't published this one yet to the registry, as I still have a few more testing tweaks. Have you tested any from this cloned repo @williejay2017 ?

**Comment by williejay2017** [comment]
@chuckcarpenter -  I had some issues but made some small changes and added some personal flavor and since I know you guys are super busy , I published it for use until your version is up and going.
