### ISSUE TITLE
Button Event Bindings Lost Between Route Transitions

### ISSUE THREAD

**Issue by nadnoslen** [shipshapecode/react-shepherd#23]
I was trying out the `react-shepherd` component and noticed that when returning to a page that had the tour embedded within that the event bindings (e.g. `next`, `cancel`, etc.) were being lost on returning to the page.

Turns out the mapping of the buttons seems to be forgetting to return the `type` attribute.

PR to follow.

**Comment by chuckcarpenter** [comment]
closed by #24

**Comment by nadnoslen** [comment]
Hey @chuckcarpenter, do you have plans to cut a new release (or release-candidate) any time soon?  I know you're probably working out the kinks from the `shepherd.js` major version changes.  No pressure.

**Comment by chuckcarpenter** [comment]
@nadnoslen let me get one out for you this week so you can test and provide any further feedback, if that works for you?
