### ISSUE TITLE
Readme example broken

### ISSUE THREAD

**Issue by ashnur** [shipshapecode/react-shepherd#236]
`import {ShepherdTour, ShepherdTourContext} from 'react-shepherd'`

ShepherdTourContext is undefined.

**Comment by rwwagner90** [comment]
Looks like it is defined in our code https://github.com/shipshapecode/react-shepherd/blob/master/src/index.tsx#L63

What version are you using @ashnur?

**Comment by ashnur** [comment]
I am looking at the dist files in the distributed node package from npm, and the Context is not exported. Maybe some changes weren't published to npm?

**Comment by ashnur** [comment]
└── react-shepherd@2.1.0

**Comment by ashnur** [comment]
The example folder does contain an example similar to the readme, but the tests are not using the Context, the changes in October were not implemented with tests covering them. I am assuming here, perhaps wrongly, that if I would use a development build, it would work.

**Comment by rwwagner90** [comment]
@chuckcarpenter can you take a look at this?

**Comment by ashnur** [comment]
just
`wget https://registry.npmjs.org/react-shepherd/-/react-shepherd-2.1.0.tgz` 
and see the files in the dist directory.

**Comment by rwwagner90** [comment]
Looks like there have been 183 commits to master since 2.1.0, so I suspect we just need to release a new version.

**Comment by chuckcarpenter** [comment]
@ashnur in the meantime, the current release example and docs can be seen here: https://github.com/shipshapecode/react-shepherd/pull/71/files

Thanks for the ping on us not releasing this change!

**Comment by ashnur** [comment]
> in the meantime, the current release example and docs can be seen here: https://github.com/shipshapecode/react-shepherd/pull/71/files

I install the package from github using `npm i shipshapecode/react-shepherd` and it compiles since I have everything necessary in the dependencies already, but it's not ideal. : )

**Comment by chuckcarpenter** [comment]
@ashnur released v3 today and docs should now all sync up!
