### ISSUE TITLE
Unable to mark button as "disabled"

### ISSUE THREAD

**Issue by nathggns** [shipshapecode/react-shepherd#284]
It seems not possible to mark a button as disabled in the steps provided, which is possible in the underlying Shepherd library.

**Comment by rwwagner90** [comment]
@chuckcarpenter do we not pass options to the buttons from here?

**Comment by chuckcarpenter** [comment]
@rwwagner90 I just matched the button factory function in here: https://github.com/shipshapecode/ember-shepherd/blob/master/addon/utils/buttons.js#L34

But I could just map the action and spread everything else passed in.

**Comment by rwwagner90** [comment]
@chuckcarpenter looks like we need to add `disabled` and `label` to the factory function, both here and in ember-shepherd.
