### ISSUE TITLE
Meaningless return value from Array.prototype.forEach

### ISSUE THREAD

**Issue by uniqname** [shipshapecode/react-shepherd#286]
https://github.com/shipshapecode/react-shepherd/blob/7510f86815d25a24648d5d628aa55a74f6970781/src/index.tsx#L29

`forEach` doesn't return anything so return values from the function argument is meaningless. It's meant either for side effects, or mutation -- though the later should probably be avoided if possible. Should we use `Array.prototype.map` instead?

**Comment by chuckcarpenter** [comment]
@uniqname I believe we actually don't want to return something there, but it's true we're mutating. Could be more explicit. 

```
  const parsedStepsforAction = steps.map((step: Step.StepOptions): Step.StepOptions => {
    const { buttons } = step;

    if (buttons) {
      step.buttons = buttons.map((button: ShepherdStepWithType) => {
        const { type, classes, text, action } = button;
        return {
          // TypeScript doesn't have great support for dynamic method calls with
          // bracket notation, so we use the `any` escape hatch
          action: action || (tour as any)[type!],
          classes,
          text,
          type
        };
      });
    }

    return step;
  });

  parsedStepsforAction.forEach((step: any) => tour.addStep(step));
```

**Comment by chuckcarpenter** [comment]
refactored: https://github.com/shipshapecode/react-shepherd/blob/master/src/index.tsx#L38
