### ISSUE TITLE
Seeking documentation on class components

### ISSUE THREAD

**Issue by Sergio16T** [shipshapecode/react-shepherd#317]
Our codebase uses both Hooks and Classes, I tried looking back at TourMethods in previous versions and still had trouble. Curious to know if the library still supports both?

**Comment by Sergio16T** [comment]
Reading through the closed issues, I realize I will have to install v2.1.0 of this package

**Comment by Sergio16T** [comment]
Would be awesome if future release supports both hooks and classes. Thanks for the amazing library!

**Comment by chuckcarpenter** [comment]
@Sergio16T would you be able to help us try that out? From what I see, the component still exports context for you to use the v2 pattern. So, you'd import `TourMethods` and use it like in the previous example. I believe the API is still there for it:

```
        <ShepherdTour steps={steps} tourOptions={tourOptions}>
          <TourMethods>
            {(tourContext) => (
              <button className="button dark" onClick={tourContext.start}>
                Start Tour
              </button>
            )}
          </TourMethods>
```

Happy to try to find a way to support both, but I'm not well versed in context using the class component pattern.

**Comment by Sergio16T** [comment]
Had Trouble getting the source zip files with my work laptop so we went with another library in the interest of speed and have since implemented the product tour. However to help, I installed React-Shepherd in a local project on my mac book pro and had no problem installing the zip files and just tested both Hooks and Classes and they are both working as documented. 

Would be helpful if there was documentation on triggering tourContext.start() on componentDidMount. Tried creating wrapper and attempting to access via props, I didn't see in the documentation any examples of there being a consumer to provide context methods to children. How do you start the tour when the component mounts ?

**Comment by chuckcarpenter** [comment]
@Sergio16T `this.props.tourContext` wasn't available to you? I think you'd pass it down using my example and then those props could be accessed in the lifecycle method. I originally found the info here: https://github.com/facebook/react/issues/12397

Perhaps try a code sandbox?

**Comment by Sergio16T** [comment]
Yes that is exactly what I attempted to do. 
In Parent 
`
 return (
      <div className="App">
        <ShepherdTour steps = {steps} tourOptions={tourOptions}>
            <TourMethods>
                ({tourContext}) => (
                    <NavTabs data={tabData} tourContext={tourContext}/>
                ); 
            </TourMethods>
        </ShepherdTour>
      </div>
    )
`
In Child 

`
class NavTabs extends Component {

    componentDidMount() {
        this.props.tourContext.start();  
    }
  render() {
    const { data } = this.props
    return (
   
      <NavTabs >
        <TabList>
          {data.map(tab =>
            <Tab>
              {tab.label}
            </Tab>
          )}
        </TabList>
        <ContentPanels>
          {data.map(tab =>
            <TabPanel>
              {tab.content}
            </ContentPanel>
          )}
        </TabPanels>
      </NavTabs>
    )
  }
}
`

**Comment by Sergio16T** [comment]
It's telling me tourContext is undefined at line below TourMethods

**Comment by chuckcarpenter** [comment]
@Sergio16T I have a working example here: https://codesandbox.io/s/affectionate-dream-eckxv

Not sure how yours differs, but this definitely works. Let me know if you discover some edge case.

**Comment by Sergio16T** [comment]
I apologize I had created an app2 to experiment with and didn't update the import in index.js with ReactDOM.render()

The App import had the hooks example.. 

everything is working correctly

**Comment by Sergio16T** [comment]
Thanks very much for your help! I apologize for the confusion. The app2 had the class components.. everything was working fine
