### ISSUE TITLE
react-shepard.now.sh is broken

### ISSUE THREAD

**Issue by b-zurg** [shipshapecode/react-shepherd#401]
![image](https://user-images.githubusercontent.com/57298613/88341328-1ad82880-cd46-11ea-89a2-8cffd2a3cd87.png)

**Comment by rwwagner90** [comment]
@chuckcarpenter I don't know if that ever worked? Can we remove all the experiments you started?

**Comment by chuckcarpenter** [comment]
It never worked right, but I didn't realize that Vercel updated the about section of the repo with it's permissions. I'll reset.

**Comment by chuckcarpenter** [comment]
@b-zurg set the link back to our GH pages link, https://shipshapecode.github.io/react-shepherd/
