### ISSUE TITLE
tour is null

### ISSUE THREAD

**Issue by srodriki** [shipshapecode/react-shepherd#402]
Hey shepherd team! I'm doing a very basic usage of this wrapper with a single step tour and following your example almost line by line. However, the call to useContext(ShepherdTourContext) returns a null value. 

Here's my code:

```js
import React, { useContext} from 'react'
import { ShepherdTour, ShepherdTourContext } from 'react-shepherd'

const tourOptions = {
   /*options */
}

const steps = [
  {
    /* single step config*/
  }
]
const MyComponent = props => {
  const tour = useContext(ShepherdTourContext) // tour is null!!
  
return (
  <div class="my-component">
     <ShepherdTour steps={steps} tourOptions={tourOptions}>
            <!-- the following line throws an exception during rendering because tour is null -->
            <button onClick={tour.start}>Start</button> 
     </ShepherdTour>
  </div>
)
}
```

any help is much appreciated!!

**Comment by chuckcarpenter** [comment]
@srodriki could you provide a code sandbox to help us see an example? What you show here looks fine, but perhaps there are details missing. e.g., https://codesandbox.io/s/admiring-hellman-23nzm?file=/src/App.js:622-641

**Comment by srodriki** [comment]
@chuckcarpenter I got to reproduce the issue with this: https://codesandbox.io/s/busy-tereshkova-unl1j?file=/src/App.js

So basically the main difference is I moved the "ShepherdTour" component inside the same component that references the tour object. Maybe that's a mistake on my end?

**Comment by chuckcarpenter** [comment]
@srodriki you're declaring the context before the provider, so no I don't think that'll work.

**Comment by srodriki** [comment]
@chuckcarpenter 

thanks man! much appreciated. closing now!
