### ISSUE TITLE
Feature request:  Add Typescripts Typings to the React Wrapper

### ISSUE THREAD

**Issue by lockettks** [shipshapecode/react-shepherd#41]
Great library- I just started using it and am enjoying it.  It would be helpful to include the typings with this react wrapper project.  I see that some typings were written for the original shepherd.js as part of
https://github.com/shipshapecode/shepherd/blob/master/src/js/step.js#L32-L89
but with this project I'm having to write my custom types in order to make Typescript happy.
Thanks in advance

**Comment by chuckcarpenter** [comment]
@lockettks glad you like it! We'd be happy to take a PR that included the typings you had to create, if you would be willing?

**Comment by lockettks** [comment]
Great!  I can’t promise when I’ll get it done, but I’ll be glad to help however I can.  I’ll probably start with just copying the typing files from your shepherd.js project over, and see how those work out.

**Comment by rwwagner90** [comment]
@lockettks we're definitely not pros at TypeScript here, but Shepherd itself should have the types, so we just need to ensure this wrapper uses them.
