### ISSUE TITLE
Consider exporting more types

### ISSUE THREAD

**Issue by shepmaster** [shipshapecode/react-shepherd#418]
I'd like to declare my steps and button arrays as typed constants: 

```ts
const steps: ? = [];
const buttons: ? = [];
```

However, types like `ShepherdOptionsWithType` aren't exported:

```
Module '"../node_modules/react-shepherd/dist"' declares 'ShepherdOptionsWithType' locally, but it is not exported.
```

**Comment by shepmaster** [comment]
As a workaround, I'm using

```ts
type ExtractProps<P> = P extends FunctionComponent<infer T> ? T : never;
type Steps = ExtractProps<typeof ShepherdTour>['steps'];
```

**Comment by rwwagner90** [comment]
@shepmaster we're not purposefully hiding anything with types. Please feel free to open a PR on the Shepherd repo adding or exporting whatever types you need 😃
