### ISSUE TITLE
'data-popper-reference-hidden' attribute is not being removed when the step gets called. 

### ISSUE THREAD

**Issue by JakeGreer** [shipshapecode/react-shepherd#476]
Would there be some sort of silent error that causes the step not to show. I get strange behavior where once the step is called, the overlay shows, the element gets highlighted and the show/hide functions get called, but the text box does not appear. I can see the element in the DOM with the attribute `data-popper-reference-hidden` attached to it, and if I delete it the box shows. Any suggestions on what would be causing this error. The step itself seems pretty basic 

```
{
    id: "StepID",
    attachTo: { element: ".test-btn", on: "left" },
    buttons: [
      {
        classes: "shepherd-button-secondary",
        text: "Back",
        type: "back",
      },
      {
        classes: "shepherd-button-primary",
        text: "Next",
        type: "next",
      },
    ],
    highlightClass: "highlight",
    scrollTo: false,
    cancelIcon: {
      enabled: true,
    },
    title: "Test",
    text: [
      'Testing 123,
    ],
    when: {
      show: () => {
        console.log("Shown");
      },
      hide: () => {
        console.log("Hide");
      },
    },
  },
```

**Comment by JakeGreer** [comment]
It seems to only be happening if I have the developer console open. Super strange. Maybe there is not enough room for the element to show? Not sure.

**Comment by rwwagner90** [comment]
@JakeGreer yeah, I think it gets hidden if you scroll to a place where it cannot fit to display.

**Comment by cenkce** [comment]
I live this problem too.

**Comment by cenkce** [comment]
Shepherd-modal's position is correct but keep hidden.

**Comment by rwwagner90** [comment]
@cenkce it's hidden if it doesn't have room to be displayed on your screen

**Comment by cenkce** [comment]
I can't understand what the room means? Page has enough spaces to show dialog if you mean that.

**Comment by cenkce** [comment]
<img width="936" alt="Screen Shot 2020-11-03 at 16 03 34" src="https://user-images.githubusercontent.com/176122/97988597-4317fe80-1dee-11eb-9c11-6824df8810b4.png">

**Comment by rwwagner90** [comment]
@chuckcarpenter do we have anything specific to this react wrapper that might be causing this? There definitely seems like plenty of room here.

**Comment by cenkce** [comment]
Display dialog for Name field but I click next then it keeps hidden. What do you recommend?

**Comment by cenkce** [comment]
I use a scrollbar component and when I remove it then it works as expected.

**Comment by chuckcarpenter** [comment]
@JakeGreer or @cenkce any chance you guys could setup a basic code sandbox where this is replicated? The demo site, https://shipshapecode.github.io/react-shepherd/, works fine even when I have devtools open.

**Comment by rwwagner90** [comment]
This seems like a bug with custom scroll wrappers. I propose we close as wontfix @chuckcarpenter
