### ISSUE TITLE
Declaration or statement expected

### ISSUE THREAD

**Issue by OAnouman** [shipshapecode/react-shepherd#553]
Hi, i got an error  on import

```import { ShepherdTour, ShepherdTourContext } from 'react-shepherd```

Error: 
```TypeScript error in .../node_modules/react-shepherd/dist/index.d.ts(18,1)```

```
     6 | declare const ShepherdTourContextConsumer: React.Consumer<Shepherd.Tour | null>;
     17 | export declare const ShepherdTour: FunctionComponent<ShepherdProps>;
  > 18 | export type { default as Step } from 'shepherd.js/src/types/step';
       | ^
     19 | export type { default as Tour } from 'shepherd.js/src/types/tour';
     20 | export { ShepherdTourContextConsumer as TourMethods, ShepherdTourContext };
```

My modules: 
+ "react-shepherd": "^3.3.2",
+ "typescript": "~3.7.2",

Need some help. Any fix??

Thanks

**Comment by rwwagner90** [comment]
@chuckcarpenter @r0bc4ry do either of you have time to look at this?

**Comment by OAnouman** [comment]
Hello, still no solution ?

**Comment by chuckcarpenter** [comment]
@OAnouman have you tried newer versions of TS? I'm using `typescript@4.1.2` and don't see this issue. Otherwise, perhaps create a code sandbox to replicate the exact error?

**Comment by OAnouman** [comment]
Hi @chuckcarpenter 
I will try and make a feedback.

**Comment by chuckcarpenter** [comment]
@OAnouman please open this back up if you can replicate with the latest version

**Comment by npedrini** [comment]
@chuckcarpenter I'm also using `typescript@^3.7.0` and seeing the same error. Unfortunately, my project is within a monorepo and typescript is a root-level dependency and beyond my control. Would be much appreciated if there was a recommended workaround, as currently my project won't compile.

**Comment by rwwagner90** [comment]
@npedrini what version of react-shepherd are you using?

**Comment by npedrini** [comment]
@rwwagner90 I'm using `3.3.3`. I've tried all the 3. versions as well but the behavior is the same.

**Comment by chuckcarpenter** [comment]
@npedrini is it not possible to update your project to 3.8, which supports type only exports? Otherwise, you can use an older version of this package and do your own exports. https://shipshape.io/blog/exporting-typescript-imports/

**Comment by npedrini** [comment]
@chuckcarpenter it may be, but typescript is specified as a root-level dependency in a monorepo so any updates have an impact on more than just the subproject I work on. I ended up rolling my own react integration, but might be worth considering rearchitecting how those types are exported so older versions of typescript are supported.

**Comment by chuckcarpenter** [comment]
@npedrini you can't really do both. This is the PR that introduced more exports, which before that you had to declare your own. https://github.com/shipshapecode/react-shepherd/pull/439

As I said before, pinning to an earlier version is the alternative to doing a TS 3.8 update in your project. If there's something I'm missing, we're happy to look at any pull request you think would be helpful.
