### ISSUE TITLE
Latest version not working properly

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [shipshapecode/react-shepherd#560]
![Screenshot from 2020-12-14 09-17-38](https://user-images.githubusercontent.com/69786094/102046146-b571fa80-3e00-11eb-8680-932163a373fc.png)

version 2.1.0 working like this, it highlighting selected class and popover design also good.

why version 3.3.2 is not working like version 2.1.0?

**Comment by rwwagner90** [comment]
My guess is you need to include the styles. @chuckcarpenter can you confirm what breaking changes were for 3.x?

**Comment by ravikumarjs-foyernet** [comment]
@chuckcarpenter please confirm what breaking changes were for 3.x

**Comment by rwwagner90** [comment]
@ravikumarjs-foyernet can you confirm if you are importing the styles, like we do in the example? https://github.com/shipshapecode/react-shepherd/blob/master/packages/example/src/App.js#L5

**Comment by ravikumarjs-foyernet** [comment]
No @rwwagner90

**Comment by rwwagner90** [comment]
@ravikumarjs-foyernet you have to import the styles for it to work

**Comment by ravikumarjs-foyernet** [comment]
Thank you @rwwagner90

**Comment by rwwagner90** [comment]
@ravikumarjs-foyernet does it work now?

**Comment by chuckcarpenter** [comment]
@ravikumarjs-foyernet I believe the breaking changes were around what version of Shepherd was being used. But, as @rwwagner90 suggested, your issue is around the styles import. For more info on changes, you can use this compare. https://github.com/shipshapecode/react-shepherd/compare/v2.1.0...v3.0.0

**Comment by ravikumarjs-foyernet** [comment]
Thanks @chuckcarpenter

**Comment by ravikumarjs-foyernet** [comment]
> @ravikumarjs-foyernet does it work now?

yes @rwwagner90
