### ISSUE TITLE
advanceOn does not work

### ISSUE THREAD

**Issue by vinibispo** [shipshapecode/react-shepherd#562]
I'm trying to emit a click event on an element, but that is not working.
[docs:options.advanceOn](https://shepherdjs.dev/docs/Step.html)

**Comment by rwwagner90** [comment]
@vinibispo sorry to hear you are having trouble, but the option should work. We would need much more info to help diagnose the problem further. Can you share some code?

**Comment by vinibispo** [comment]
'course
I did this code sandbox to clearify
 [Sandbox](https://codesandbox.io/s/blissful-margulis-rzmmu)

**Comment by rwwagner90** [comment]
@vinibispo clicking profile advances the tour for me in your sandbox. Does it not for you?

**Comment by vinibispo** [comment]
Sorry @rwwagner90 I was thinking in the other way, if I would click on next, that makes click on profile automatically.
Is there a way to click on next and that fire the click?

**Comment by rwwagner90** [comment]
@vinibispo yeah, you can use custom actions on buttons.

```js
action() {
    // Open profile here, then advance the tour
    return this.next();
  }
```
