### ISSUE TITLE
stepsContainer option not working for typescript react project

### ISSUE THREAD

**Issue by tomish0** [shipshapecode/react-shepherd#563]
https://codesandbox.io/s/modest-volhard-yyrf6

**Comment by rwwagner90** [comment]
@tomish0 your example does not have any way to start the tour. Can you please include an example showing the bug?

**Comment by rwwagner90** [comment]
Also, we have tests for this functionality in Shepherd, so it should be working: https://github.com/shipshapecode/shepherd/blob/7530e9781a9c0114b44401cd5bd2a3ea2baad6c8/test/unit/tour.spec.js#L506

**Comment by chuckcarpenter** [comment]
@rwwagner90 I can confirm it's not working on the latest release, but does in master. https://codesandbox.io/s/happy-pine-jugd5

**Comment by chuckcarpenter** [comment]
@tomish0 this is fixed in master, so an update to 3.3.3 will take care of this. You can see the working example https://codesandbox.io/s/happy-pine-jugd5

**Comment by tomish0** [comment]
Perfect, I've updated the package, working now. Thank you!
