### ISSUE TITLE
How to add media query?

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [shipshapecode/react-shepherd#566]
not getting, how to do the responsiveness for mobile and tablet using default styles?

**Comment by rwwagner90** [comment]
@ravikumarjs-foyernet what do you mean? You can override any of the styles as you see fit.

**Comment by ravikumarjs-foyernet** [comment]
I mean how to design it for mobile screen?

**Comment by rwwagner90** [comment]
@ravikumarjs-foyernet however you want. This is 100% dependent on how you want it to look.
