### ISSUE TITLE
transition between step changes

### ISSUE THREAD

**Issue by yairEO** [shipshapecode/react-shepherd#567]
Would be nice if the steps changed from one another with a feel of each, where the highlighted area moves with transition and the info "buble" as well.

This other script does it well in the demo page
https://github.com/elrumordelaluz/reactour

But that script is extremely poor with step settings and seems to be abandoned by its creator, while react-shepherd has a good set of `step` settings allowing me greater manipulation, but still.. without smooth transitions it looks bad (IMHO)

**Comment by yairEO** [comment]
related to - https://github.com/shipshapecode/shepherd/issues/82#issuecomment-773504573

**Comment by rwwagner90** [comment]
@yairEO have you tried using CSS transitions for this?

**Comment by yairEO** [comment]
Thanks! 

No, I didn't want to spend time converting all my website's already-existing tour component without being absolutely certain animations betweens teps are possible. 

Why doesn't the demo have this by default? 
it would really help in making a decision when "shopping" for tour/walkthrough scripts for a project.

**Comment by rwwagner90** [comment]
@yairEO it hasn't been a priority. If you'd like to submit some suggested transitions, we would gladly review a PR.
