### ISSUE TITLE
Tour modals don't show properly

### ISSUE THREAD

**Issue by mattveraldi** [shipshapecode/react-shepherd#570]
Hi, I'm coding an app tour with this React wrapper.
I tried the tutorial on the README just to see if everything works, but I think that something is wrong with styles.
![image](https://user-images.githubusercontent.com/26458615/111050716-85151900-844e-11eb-9362-c1d40a16d0be.png)

I'm using React Bootstrap as a design system for my app.

**Comment by rwwagner90** [comment]
@mattveraldi you must include Shepherd's CSS, if you want the default styles. Is it included in your app?

**Comment by mattveraldi** [comment]
> @mattveraldi you must include Shepherd's CSS, if you want the default styles. Is it included in your app?

Yes, I included it in `index.html` as `<link rel="stylesheet" href="shepherd.js/dist/css/shepherd.css"/>`

**Comment by rwwagner90** [comment]
@mattveraldi that does not seem like a correct path, unless you copied a `shepherd.js` folder into your app. Likely you want to import it from `node_modules`.

**Comment by OllyHodgson** [comment]
I ran into the same thing, and solved it with this import statement in my React component.

`import "shepherd.js/dist/css/shepherd.css";`

**Comment by rwwagner90** [comment]
@OllyHodgson yeah, your react app likely has a build that will import from node_modules automatically. Imports like that typically work, but things like `<link rel="stylesheet" href="shepherd.js/dist/css/shepherd.css"/>` likely will not work.
