### ISSUE TITLE
will it work with nextjs?

### ISSUE THREAD

**Issue by ankit-vinove** [shipshapecode/react-shepherd#580]
when i am trying to use the exact code it is giving me the error of window not defined?

**Comment by rwwagner90** [comment]
@ankit-vinove you'll have to not run it server side. There is no window with SSR. @chuckcarpenter does nextjs provide an easy way to mark code as client side only or would we just need to say `if(typeof window !== 'undefined')` or something?

**Comment by ankit-vinove** [comment]
yeah i tried by validating the undefined condition but as i am importing the react-shepherd it is throwing the window error there only. And i also tried using dynamic import in nextjs but the in DOM the component is not getting rendered.

**Comment by chuckcarpenter** [comment]
@ankit-vinove have you tried to load the lib as suggest dynamically? https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by karlhorky** [comment]
@chuckcarpenter just tried dynamic `import` with `ssr: false` now, along with @inespart - but it ended up not showing any tour content at all

Would be cool to get a recommendation from the maintainers as to how to use this with Next.js and other SSR frameworks

**Comment by chuckcarpenter** [comment]
@karlhorky that's fair, so i gave a quick whirl. https://codesandbox.io/s/crazy-oskar-4xiug

Basically, you need to use the `useEffect`, since it's not fired on the server.

**Comment by chuckcarpenter** [comment]
One more note, updated to work with dynamic imports, because seems like was inconsistent w/o that. Hope this helps!

**Comment by karlhorky** [comment]
Great! Would it be possible to add a small section to the readme / docs about usage in Next.js and other SSR / SSG frameworks?

**Comment by inespart** [comment]
That’s great, thank you for the update!

**Comment by CiaranPearse** [comment]
You dont need useEffect unless you want to run the tour on load.

This is working fine for me in Next 12

`import React, { useContext } from "react";
import { ShepherdTour, ShepherdTourContext } from 'react-shepherd'
import newSteps from './steps';
import "shepherd.js/dist/css/shepherd.css";

const Tour = () => {
  const tourOptions = {
    defaultStepOptions: {
      cancelIcon: {
        enabled: true
      }
    },
    useModalOverlay: true
  };

  const startTour = (t) => {
    console.log('tour: ', t)
    console.log('Start Tour')
    t.start()
  }

  const TourInstance = () => {
    const tour = useContext(ShepherdTourContext);
    return (
      <button className="button dark" onClick={(t) => startTour(tour)}>
        Start Tour
     </button>
    );
  }


  return (
    <>
      <ShepherdTour steps={newSteps} tourOptions={tourOptions}>
          <TourInstance />
        </ShepherdTour>
    </>
  );
};
export default Tour;`

**Comment by chuckcarpenter** [comment]
@CiaranPearse I think my suggestion is directed to Next 13, at least that's based on the version used in my example.
