### ISSUE TITLE
Multiple tours ReactJS

### ISSUE THREAD

**Issue by UtopiaEH** [shipshapecode/react-shepherd#583]
How to create multiple tours for different modules or separate pages ReactJS

**Comment by rwwagner90** [comment]
@UtopiaEH Multiple tours at once are not permitted. You'll want to use one tour and setup different sets of steps.

**Comment by timothyallan** [comment]
Hmmm. Any recommended way to segregate/partition a tour to handle multiple pages, or does each page/area/module just have to keep track of which step to show/start/end with?  We have an enterprise app with dozens of separate modules we were going to use this for and adding/removing steps to a single tour would soon become a nightmare, each of our modules would have to update their step #'s accordingly for every change.

**Comment by rwwagner90** [comment]
@timothyallan you can separate the steps however you would like.

```js
const steps1 = [/* array of steps */];
const steps2 = [/* array of steps */];
```

You can totally replace the tour with a new one when you load up a new module, if you'd like. The thing that is not supported is running multiple active tours at the same time.

**Comment by timothyallan** [comment]
> @timothyallan you can separate the steps however you would like.
> 
> ```js
> const steps1 = [/* array of steps */];
> const steps2 = [/* array of steps */];
> ```
> 
> You can totally replace the tour with a new one when you load up a new module, if you'd like. The thing that is not supported is running multiple active tours at the same time.

Awesome, thanks for the clarification. That'll work well.

**Comment by UtopiaEH** [comment]
yes I did and I did distribute the steps at the time, but I thought it was possible to make different copies for him

sorry use Google Translate :D
