### ISSUE TITLE
upgrade React version in peer dependency to 17.

### ISSUE THREAD

**Issue by seiry-apt** [shipshapecode/react-shepherd#584]
Is it possible to bump the deps version?

**Comment by rwwagner90** [comment]
@chuckcarpenter any reason not to update? We should probably setup dependabot.

**Comment by chuckcarpenter** [comment]
https://reactjs.org/blog/2020/08/10/react-v17-rc.html

Looks like it's pretty low risk, @seiry-apt could you submit a PR from your fork? Otherwise, I'll try to update in the next couple of days. 

@rwwagner90 it's setup on here, but I don't think does anything for peer dependencies.

**Comment by chuckcarpenter** [comment]
@seiry-apt have you tested this? I tried and was having some issues locally, but an example on https://codesandbox.io/s/admiring-hellman-23nzm seems to be working fine.
