### ISSUE TITLE
Reset canClickTarget when next step is attachedTo same element 

### ISSUE THREAD

**Issue by CharlotteArai** [shipshapecode/react-shepherd#585]
Hi! 
So I have 2 steps in my tour that are attached to the same element. 
In step 1 the element is disabled (canClickTarget:false) and in step 2 the element should be enabled (canClickTarget:true). 
But I can't figure out how to update the canClickTarget in step 2. 

Any help is much appreciated!
Many thanks 😀

**Comment by chuckcarpenter** [comment]
@CharlotteArai could you provide an example, perhaps in something like https://codesandbox.io ?

**Comment by CharlotteArai** [comment]
Thanks for your reply!
Here's an example: https://codesandbox.io/s/react-shepherd-clickable-elements-1669x

Maybe it's working as expected and the canClickTarget can't be 'reset' in between steps? 
It would be easier if the canClickTarget could be 'toggled' between steps, but it's not a big issue, I solved it by attaching the step to a child element instead (step 3 in sandbox).

**Comment by chuckcarpenter** [comment]
@CharlotteArai no, you're right, it should reset and so that appears to be a bug. Thanks for the example, it really helps. It appears that once we add the disabled class, we don't reset it. https://github.com/shipshapecode/shepherd/blob/695936b3b51442b2aa2cf9985a528cf4d0b959f7/src/js/step.js#L420

**Comment by chuckcarpenter** [comment]
fix in https://github.com/shipshapecode/shepherd/pull/1544, but will require a release in the main lib

**Comment by CharlotteArai** [comment]
That's great, many thanks! 👍
