### ISSUE TITLE
position absolute;  inset: 0 auto auto 0 

### ISSUE THREAD

**Issue by rodbs** [shipshapecode/react-shepherd#586]
In understand that by default the box is position next to the highlighted object with 
```position absolute;  inset: 0 auto auto 0 ```

Is there a way to move it  the box or put some space between them (inset: 5px, ...) ? Can this position be controlled anyhow?

Thanks!

**Comment by rwwagner90** [comment]
@rodbs yes, Shepherd uses popper behind the scenes. Check out the `offsets` section of https://shepherdjs.dev/docs/tutorial-04-cookbook.html
