### ISSUE TITLE
Redux breaks tour object

### ISSUE THREAD

**Issue by andreastepel** [shipshapecode/react-shepherd#588]
I need to personalize some content inside each step for my users. Therefore I am wrapping my Redux Provider outside the `<ShepherdTour/>` component. As soon as I am using the `connect()` function for my App.js the tour object becomes inaccessible (e.g. tour.next(), tour.isActive()). 
  
Anyone experiencing this issue as well?

**Comment by chuckcarpenter** [comment]
@andreastepel perhaps post an example from codesandbox ?

**Comment by CharlotteArai** [comment]
To get access to redux in your steps.js maybe you could just import the store? 

`import { store } from '../../app'`

and in app or wherever you configure your store 
`export const store = configureStore();`

This way you'll get access to getState() (and other things such as dispatch)
Hope this helps 🤓
