### ISSUE TITLE
Arrow padding as a function does not work

### ISSUE THREAD

**Issue by null00** [shipshapecode/react-shepherd#598]
Latest version of popper supports setting up the arrows padding as a function according to the docs: [Arrow padding](https://popper.js.org/docs/v2/modifiers/arrow/#padding).

Seems that react-shepherd is using an older version of popper which does not support that.

Proof: [Sandbox](https://codesandbox.io/s/zealous-kilby-1z2d0?file=/src/App.js)

Is there any chance of getting that popper updated to latest version?

Thanks,
J

**Comment by chuckcarpenter** [comment]
@null00 this should be in v3.3.6 now published

**Comment by null00** [comment]
Thanks @chuckcarpenter for your quick actions!

Works like a charm :)
