### ISSUE TITLE
add info about install original package for styling

### ISSUE THREAD

**Issue by popuguytheparrot** [shipshapecode/react-shepherd#602]

**Comment by chuckcarpenter** [comment]
@popuguytheparrot could you add more info here, I'm not clear what you mean exactly?

**Comment by popuguytheparrot** [comment]
i install only react wrapper and when i was try to use, got unexpected broken styles.

**Comment by chuckcarpenter** [comment]
Did you import the default CSS? e.g., https://github.com/shipshapecode/react-shepherd/blob/v3.3.4/packages/example/src/App.js#L5

**Comment by ShunyaWatanabe** [comment]
Hi, thanks for developing such an awesome library! I'm so far liking how easy it is to implement an onboarding UX using react-shephered.

One thing that confused me is that I needed to add the below line for the modal to look fine, which you mentioned in the above comment.

```
import "shepherd.js/dist/css/shepherd.css";
```

It might be good to add this in README?
