### ISSUE TITLE
button type cancel dont close popover

### ISSUE THREAD

**Issue by popuguytheparrot** [shipshapecode/react-shepherd#603]
```
buttons: [
            {
                type: 'cancel',
                classes: 'shepherd-button-secondary',
                text: 'Exit',
            },
            {
                type: 'next',
                text: 'Next',
            },
        ],
```

**Comment by chuckcarpenter** [comment]
@popuguytheparrot can you share a codesandbox with an example? Still seems to work here https://shipshapecode.github.io/react-shepherd/ and here with v3.3.6 https://codesandbox.io/s/competent-marco-evlw9

**Comment by popuguytheparrot** [comment]
Yep, there work fine, but in my app doesn't. I tried reproduce, but is going fine 🤨
