### ISSUE TITLE
Can steps have react component content, not just text?

### ISSUE THREAD

**Issue by jtheis85** [shipshapecode/react-shepherd#612]
I am considering using react-shepherd for a mature commercial project. We have a fair number of non-interactive elements (e.g. SVG icons, text parsing and styling, etc) encapsulated by React components.

Can react-shepherd steps include arbitrary react component content? All the examples I see only use the "text" element, which is likely not sufficient for us. https://shepherdjs.dev/docs/Step.html has:

> The text in the body of the step. It can be one of three types:
> 
> - HTML string
> - `HTMLElement` object
> - `Function` to be executed when the step is built. It must return one the two options above.

I would rather not be limited to manually reproducing everything already handled in react components as raw HTML. Is there some way the `Function` option can be used  for this purpose? Or something else I'm missing?

**Comment by rwwagner90** [comment]
Hi @jtheis85, thanks for reaching out. Can you please clarify what you mean exactly? You want to display elements from the page like SVGs etc inside the tooltip itself?

**Comment by jtheis85** [comment]
Inside of this area:
![image](https://user-images.githubusercontent.com/2453292/149408484-01d9dfde-8d0a-41a0-85c9-bcfaff130fe7.png)

Instead of plain text, want to be able to render arbitrary React components like `<MyReactComponent  someProps={...})/>`.

(For SVG specifically, I was just giving examples of the *kinds* of react components I would like to use.  I am not interested in whether raw SVG HTML tags can be used in that area. I want to use *React Components* that *render* SVG, as well as other React components that do all sorts of other things in our existing app).

**Comment by rwwagner90** [comment]
@jtheis85 gotcha, I suppose I don't understand the use case still though. Do you have an example of what you would be putting inside the tooltip? I get you want to reuse react components, but shouldn't those components be on your page and you highlight them with Shepherd vs putting them inside the tour tooltip?

**Comment by jtheis85** [comment]
Yes, I understand that Shepherd points to existing React components on the page. It will often be important for our explanatory content *inside the tour tooltip* to include React components.

When explaining parts of our app to users, we may want to leverage formatting, icons, images, navigation buttons, links, embedded videos, and other rich content. We have an extensive existing library of react components that render these things and hook into our app in various ways. We have react components that generate formatted text based on parsing an in-house encoding grammar. There's react components for domain-specific presentations of what I'll call "mathematical formulas" for the purpose of this discussion. Color and styling needs to hook into our dynamic theming system, which uses the React styled-components library.

Would it be possible to recreate some of that stuff *outside* of the existing react components for use inside of shepherd? Sure. It would take a bunch of time, and be an ongoing maintenance burden to keep both versions up to date. So I'm not fond of that option, and would likely create my own shepherd clone based on Popper which is "natively React" instead.

Hopefully that is enough explanation as to why I want to render React content inside of a react-shepherd tour.

So now the question is, can it be done?

**Comment by m1073496** [comment]
Hi @jtheis85, the tool tip area you're looking to modify is represented by the text step option which must resolve to either an:
-  HTML string
- `HTMLElement` object
- `Function` to be executed when the step is built. It must return one the two options above.

To get your arbitrary React components to resolve to an HTML string, you can [import ReactDOMServer](https://reactjs.org/docs/react-dom-server.html) and pass your component into one of the following ReactDOMServer methods: 
- renderToString()
- renderToStaticMarkup()

We've created a small sandbox to demonstrate this solution [here](https://codesandbox.io/s/festive-star-6h0yq?file=/src/steps.js) if you'd like to take a look. Let us know if this helps and if you have any more questions!

**Comment by jtheis85** [comment]
@m1073496 thanks! This is helpful, I appreciate the working example. 

It seems a bit round-a-bout, but it looks like that's the best that can be done in terms of React/shepherd interop. I guess the underlying Shepherd API doesn't leave room for many other options.

I'll consider my issue closed.

**Comment by rwwagner90** [comment]
@jtheis85 if you could please respond back when you have your tour implemented, I would love to see some real world examples of the types of steps you're going for 😃

**Comment by Nate-Wessel** [comment]
IMO, this seems like a pretty obvious thing one would want to do. React projects use little components all over the place, but here they have to be convertible to an HTML string? What about state, event listeners, context, etc? 

Simple use cases would include:
* pointing out something on the page while directly referencing it inline. E.g. an icon on a map.
* using components that rely on context like `react-router`'s `Link`

And also it would just be nice to be able to keep writing things in JSX like the rest of my code. 

But I guess the tour elements here aren't actually created directly by React(?), so would be outside of the DOM tree that React is responsible for.

**Comment by rwwagner90** [comment]
@Nate-Wessel this library is meant to be usable by anyone, not just people using React. It is not built in React. We have wrappers for frameworks. Like https://github.com/shipshapecode/react-shepherd

Perhaps we could do some work there to make things more user friendly for React devs? The underlying code is written in Svelte, so doing things with other frameworks out of the box is going to prove difficult. We need a layer to setup some of this.

**Comment by chuckcarpenter** [comment]
@Nate-Wessel I've been trying to think about a way to use this more streamlined with a React app's components. Seems like a really wide use case though and so I'm not really wrapping my head around a good implementation. I'd assume we're extend the Tour and Step classes and perhaps do something instead of this https://github.com/shipshapecode/react-shepherd/blob/master/packages/lib/src/index.tsx#L59

Aside from that though, I think it's just not clear what needs to be done to get this going in a more useful way. Happy to look at a PR or sandbox though, if that would help.

**Comment by Nate-Wessel** [comment]
> @Nate-Wessel I've been trying to think about a way to use this more streamlined with a React app's components. Seems like a really wide use case though and so I'm not really wrapping my head around a good implementation. I'd assume we're extend the Tour and Step classes and perhaps do something instead of this https://github.com/shipshapecode/react-shepherd/blob/master/packages/lib/src/index.tsx#L59
> 
> Aside from that though, I think it's just not clear what needs to be done to get this going in a more useful way. Happy to look at a PR or sandbox though, if that would help.

From my limited understanding of how Shepherd works, I think what would be needed here would be to bring all of the Shepherd DOM manipulation into React World. That is, when the tour needs to pop up, let React actually render the entire tour component itself rather than e.g. having Shepherd attach some elements to the document `<body/>`. This would keep that element within React's control, and any content in the tour within the context of any higher-level React components. That's the only way I can think of using something like `react-router-dom`'s `<Link/>` within a tour - it would need to be within the `<Router/>` context that wraps my application. 

This library would have to tell React what to render and when. But it would have to let React handle all that action. 

If that were possible, then rendering arbitrary components inside a tour step would be super easy. 

But as I write this, I'm realizing this sounds like a pretty big ask.

**Comment by chuckcarpenter** [comment]
@Nate-Wessel Agreed that this library would have to override quite a bit of vanilla Shepherd to support that use case. I don't believe we have the capacity for that kind of rewrite, but would support in any way PRs that would move toward that and do a major release for it.

**Comment by pate3345** [comment]
In my project, I'm unable to utilize the React DOM server due to conflicts.
 can't use this method as well
                            renderToString()
                            renderToStaticMarkup()

Is there any alternative way?

Thanks.

**Comment by chuckcarpenter** [comment]
@pate3345 offhand, no I don't. That said, we've been thinking about a rewrite of this that's more than just a wrapper, but a more straightforward implementation with React focus. I know that's not a now answer, but as I look at that more perhaps I can play around with ways to make JSX (albeit, I won't what other features you'd like e.g., hooks) and other aspects a bit more drop in.
