### ISSUE TITLE
Documentation discrepancy. `button.type` and `button.action`

### ISSUE THREAD

**Issue by dkeele** [shipshapecode/react-shepherd#614]
The `react-shepherd` [readme](https://github.com/shipshapecode/react-shepherd#steps) uses the `type` key to define steps. This key is not listed on the [overall docs](https://shepherdjs.dev/docs/Step.html), it appears that `button.action` has taken its place.

When using `action` in the place of `type` in the example on the readme, `this` is undefined. It's impossible to call event methods like `this.cancel`, or `this.next`.

When using `action` in addition to `type`, neither `action` nor `type` have any effect.

**Comment by brsc2909** [comment]
How are you defining your button? I'm doing like so and it works perfectly.
```javascript
    {
      classes: "shepherd-button-primary",
      text: "Next",
      // CORRECT
      action() {
        return this.next();
      },
    },
```

You may be making the same mistake I originally did by defining it with `action` as the key and then an arrow function, which will not work.
```javascript
    {
      classes: "shepherd-button-primary",
      text: "Next",
      // WRONG
      action: () => {
        return this.next();
      },
    },
```

**Comment by dkeele** [comment]
Oh duh! That was it! Thanks!

Remaining question: Which is the preferred method to advance to the next step? `type: "next"` or `this.next()`?

**Comment by chuckcarpenter** [comment]
@dkeele as in the example, if you pass in a type then an action isn't required. e.g., https://github.com/shipshapecode/react-shepherd/blob/master/packages/example/src/steps.js#L27

**Comment by rwwagner90** [comment]
I would recommend `this.next` just to be closer to the Shepherd API.
