### ISSUE TITLE
the  link  404

### ISSUE THREAD

**Issue by zxhycxq** [shipshapecode/react-shepherd#644]
https://shipshapecode.github.io/react-shepherd/

![image](https://user-images.githubusercontent.com/11674203/176588972-efa38176-529e-4a8b-9aac-10fa9fa324fa.png)

**Comment by bennett1412** [comment]
The documentation site still seems to be broken? 
![image](https://user-images.githubusercontent.com/34763279/197351543-2cf605be-203a-44f8-89b5-cf9e2de4e6b3.png)

**Comment by chuckcarpenter** [comment]
@bennett1412 looks like 43rd time is the charm! https://shipshapecode.github.io/react-shepherd/

**Comment by chuckcarpenter** [comment]
turns out a static site doesn't like the React context so much. Probably going to move this to Vercel to simplify.

**Comment by chuckcarpenter** [comment]
@bennett1412 finally fixed and deployed. New URL: https://shipshape-react-shepherd.netlify.app/

**Comment by bennett1412** [comment]
thank you 🤝
