### ISSUE TITLE
react-shepeherd with older react version

### ISSUE THREAD

**Issue by sushmathenepalle** [shipshapecode/react-shepherd#673]
My project is currently on react version `15.7`. When I tried installing shepherd.js and imported in my project, I faced below error, 
`Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_react___default.a.createContext is not a function` because of `var ShepherdTourContext = React.createContext();`

Any workaround for this ? I even tried oldest version of react-shepherd wrapper which is `1.1.1`, same error.

**Comment by chuckcarpenter** [comment]
@sushmathenepalle there is no version of this released without a Context/Provider pattern. Have you looked at implementing with the plain JS version? https://github.com/shipshapecode/shepherd
