### ISSUE TITLE
button's  action hook doesn't work 

### ISSUE THREAD

**Issue by skymirros** [shipshapecode/react-shepherd#677]
- Here to replay: https://codesandbox.io/s/react-shepherd-forked-qwv5yx?file=/src/index.js
- Version: 4.1.0 or 3.3.3

**Comment by skymirros** [comment]
` buttons: [
      {
        classes: "shepherd-button-secondary",
        text: "Exit",
        type: "cancel",
        action(){
          this.show()
        }
      },
      {
        classes: "shepherd-button-primary",
        text: "Back",
        type: "back"
      },
      {
        classes: "shepherd-button-primary",
        text: "Next",
        type: "next"
      }
    ]`
    
    I want to use this code to do something before click EXIT button , but it doesn't work.
    While it work well with version 2.1.0

**Comment by chuckcarpenter** [comment]
@skymirros not clear on the issue as the sandbox you shared it does seem the action hook is working. e.g., 

```
{
        classes: "shepherd-button-secondary",
        text: "Exit",
        type: "cancel",
        action() {
          console.log(123123123);
        }
      },
```

which shows this console log

<img width="357" alt="image" src="https://user-images.githubusercontent.com/706378/187274015-ea9901ba-df7c-4fb6-9e22-9513f10e3e97.png">

**Comment by amosbastian** [comment]
@chuckcarpenter In his comment he says:

```
I want to use this code to do something before click EXIT button , but it doesn't work.
While it work well with version 2.1.0 
```

and the linked sandbox is version 2.1.0. Try upgrading to 4.1.0 and it stops working (I have the same problem).

**Comment by eshanaventude** [comment]
It stopped working after version 3.3.1.

**Comment by chuckcarpenter** [comment]
@amosbastian and @eshanaventude I would say that's the way it should work and that it was a bug before then. 
https://github.com/shipshapecode/react-shepherd/blob/master/packages/lib/src/index.tsx#L45

The correct way would be to just use action to do whatever you wanted and manually call an exit after.
