### ISSUE TITLE
node version does not support 12.x

### ISSUE THREAD

**Issue by itsuki0927** [shipshapecode/react-shepherd#678]
Thank you for making this package, it meets all my needs, but there is a small question, I see that shepherd.js only  `"node": "12.* || 14.* || >= 16"`, but react-shepherd needs `node > 14`, the current company pipeline Node version is 12.22.1, so I will use I can't find this package, I would like to ask if it is possible to reduce the version of this react-shepherd node for compatibility?

![image](https://user-images.githubusercontent.com/40518195/186568116-b2363b50-ee17-428e-a372-e91f7fe56b69.png)

I'm so sorry, I don't know if this will be a problem?

**Comment by chuckcarpenter** [comment]
@itsuki0927 are you no longer blocked by this issue?
