### ISSUE TITLE
Progress bar 

### ISSUE THREAD

**Issue by wlsp** [shipshapecode/react-shepherd#682]
Servus good people, 

Thank you very much for this great tool. It is a lot of fun to use and implement. I have a question though, how would I implement a progress bar in react-shepherd? 

I have looked at both documentations, shepeherd.js & react-shepherd to have a better look at the syntax. 
However, when I use the "when" method with a specific function, in this case a progress bar, I get the error: 
**react_shepherd__WEBPACK_IMPORTED_MODULE_3__.ShepherdTour.getCurrentStep is not a function.**

Where and how exactly do I call the "when" method in react-shepherd? 
And so I have implemented with many try: 

```javascript
// index.js
import React, { Fragment, useContext, useState } from 'react'
import { ShepherdTour, ShepherdTourContext, } from 'react-shepherd'
import LargeDeviceSteps from './steps';

// Setting default options for Tour
const tourOptions = {
  defaultStepOptions: {
    cancelIcon: {
      enabled: true,
    },
    scrollTo: { behavior: 'smooth', block: 'center' },
    popperOptions: {
      modifiers: [{ name: 'offset', options: { offset: [0, 20] } }]
    },
    when: {
      show() {
        const currentStepElement = ShepherdTour.getCurrentStep();
        console.log(currentStepElement)
      }
    },
  },
  useModalOverlay: true,
  keyboardNavigation: true,
};

  return (
    <div>
          <button className={styles['btn']}
            onClick={() => tour.start()}>Start</button>
     </div>
  )
}

export default function Tour({ children }) {
  return (
    <ShepherdTour 
    steps={ LargeDeviceSteps } 
    tourOptions={tourOptions}>
      {children}
      <TourInstance />
    </ShepherdTour>
  );
}
```

```javascript
//steps.js

import { STREAM, SLIDO, ..., ...., etc.. } from '../../lib/constants';

const dataSteps = [
  {
    id: 'stream',
    title: 'Stream',
    attachTo: { element: '.stream-container', on: 'right' },
    text: [`<p>${STREAM}</p>`],
    buttons: [
      {
        classes: 'shepherd-button-secondary',
        type: 'back',
        text: 'Zurück'
      },
      {
        type: 'next',
        text: 'Weiter'
      }
    ]
  },
{
    id: 'chat',
    title: 'Chat',
    attachTo: { element: '.chat-container', on: 'top' },
    text: [`<p>${CHAT}</p>`],
    buttons: [
      {
        classes: 'shepherd-button-secondary',
        type: 'back',
        text: 'Zurück'
      },
      {
        type: 'next',
        text: 'Weiter'
      }
    ]
  },
{...}
]

export default dataSteps;
```

Of course I also tried the example from the GitHub READ.ME:

```javascript
// in the steps section
....
title: 'Welcome to React-Shepherd!',
    text: ['React-Shepherd is a JavaScript library for guiding users through your React app.'],
    when: {
      show: () => {
        console.log('show step');
      },
      hide: () => {
        console.log('hide step');
      }
    }
  }
```
Thanks in advance for your support.

**Comment by chuckcarpenter** [comment]
@wlsp great question, since things are different from the vanilla JS lib. I _think_ you'd want to actually use `ShepherdTourContext` for the active instance, but I'll see if I can do a code sandbox soon to test that.

**Comment by wlsp** [comment]
Hey @chuckcarpenter , thanks for reply also for the sandbox. I appreciate it. 
May I perhaps express an idea? How about if you declare the step-index in the interface 'ShepherdProps' and give it as a number? 
i.e: 
```typescript
interface ShepherdProps {
    stepIndex?: number; //HERE
    steps: Array<ShepherdOptionsWithType>;
    tourOptions: Tour.TourOptions;
    children: React.ReactNode;
}
```

And from here on you can manipulate the tour and its behavior with the stepIndex e.g.: create a controlled tour. That when the user opens or closes a modal, the steps update themselves. 

If the tour runs through and a target element is not found, the step still shows up and this error in console is shown: The element for this Shepherd step was not found 'TARGET-CLASSNAME' - what if the step does not show up because no target was found and the tour jumps to the next step?

**Comment by chuckcarpenter** [comment]
@wlsp Would you be up for a PR to showcase more in depth what you mean? Sounds like a lot to add outside of types to me, but perhaps I misunderstood. 

I did get a functional, but not pretty solution on how you can manipulate the instance after it's created via the hook. https://codesandbox.io/s/admiring-hellman-23nzm?file=/src/App.tsx

**Comment by wlsp** [comment]
hey @chuckcarpenter, for sure I'm up to a PR. And thanks for your solution. I tried it but unfortunately I didn't get a real result.  However, if I get something done, you'll be the first to know.

**Comment by cfozil** [comment]
> https://codesandbox.io/s/admiring-hellman-23nzm?file=/src/App.tsx

Hi. Were you able to incorporate a progress bar with react?

**Comment by wlsp** [comment]
Hey @cfozil ,

unfortunately I have not been able to create a progress bar either. 
Also I haven't had the time to find a solution and keep trying.  :/

I will get organised in the new year and try to find a solution. 

By the way, you have come much further than I have! :D

**Comment by cfozil** [comment]
I was able to create it. For me it was a timing issue. So I implemented a counter. Try this and see: 
`function Tour() {
    const tour = useContext(ShepherdTourContext);
    const [count, setCount] = useState(0)

    tour.on("show", () => {
      setCount(count + 1);
    })

    useEffect(() => {
      const currentStep = tour.getCurrentStep();
      const currentStepElement = currentStep?.getElement();
      const header = currentStepElement?.querySelector(".shepherd-header");

      const progress = document.createElement('div');
      const innerBar = document.createElement('span');
      innerBar.innerText = `${tour.steps.indexOf(currentStep)}/${tour.steps.length - 1}`
      const progressPercentage = (((tour.steps.indexOf(tour.currentStep)/(tour.steps.length - 1)) * 100) - 0.8) + "%";

      //add class to the progress holder
      progress.className='shepherd-progress-bar';
      innerBar.style.width = progressPercentage;
      progress.appendChild(innerBar);
      
//skip adding progress bar to the first popup because it is a welcome dialog
      if (tour.steps.indexOf(tour.currentStep) !== 0) {
        header?.insertBefore(progress, currentStepElement.querySelector('.shepherd-cancel-icon'));
      }       
    }, [count]);
  
    useEffect(() => {
        const timeToStart = setTimeout(() => tour.start(), 2000);
      
        return() => clearTimeout(timeToStart);
      }, []);

    tour.on("complete", () => {
      setHasVisited(true);
    });
  
    tour.on("cancel", () => {
      setHasVisited(true);
    })
  
    return (
      <></>
    );
  }`
