### ISSUE TITLE
Next 13 issue - cannot read properties of undefined (reading 'context')

### ISSUE THREAD

**Issue by r1skz3ro** [shipshapecode/react-shepherd#687]
The library doesn't work with next.js version 13. Although it works locally when we run a project with `next dev` but not when we build an app with `next build && next start`. The app starts working after downgrading next to version 12.3.

codesandbox example, an error is thrown in console: https://codesandbox.io/s/react-shepherd-next-13-sd5kpn

I've forked the same working example from a different issue and bumped next.js and react - 
https://github.com/shipshapecode/react-shepherd/issues/580#issuecomment-885800218

working example from the previous issue: https://codesandbox.io/s/crazy-oskar-4xiug

**Comment by muyiwaoyeniyi** [comment]
+1

**Comment by chuckcarpenter** [comment]
@muyiwaoyeniyi great point that it's worth considering if this basic wrapper is really needed and if the base library is the way forward. Give the major version updates it might not be worth chasing. That said, will give it a swing during the holiday lull and see if I can fix @r1skz3ro

**Comment by muyiwaoyeniyi** [comment]
@chuckcarpenter Thanks for the quick response! The wrapper would still be great. That was my first option but after several hours of trying to figure out the issue above, I decided to remove any possible interaction between Shepherd and nextjs by pulling in the base library directly via a cdn.

**Comment by chuckcarpenter** [comment]
@muyiwaoyeniyi ah, I see. CDN not an ideal long term solution. I see where the issue is, so now it's more about the Shepherd.js output and React DOM 18. 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/706378/209244818-e95e1d64-e831-40d0-ae81-2c6023bb1f0f.png">

**Comment by chuckcarpenter** [comment]
the main lib uses Svelte and that's where this is crapping out: https://github.com/sveltejs/svelte/blob/master/src/runtime/internal/Component.ts#L96

So, need to figure out there what's going on. Might look at compiling in shepherd directly rather than the third layer. TBD.

**Comment by muyiwaoyeniyi** [comment]
@chuckcarpenter I see. Yea it was a fallback option when I ran out of ideas.

**Comment by amitav13** [comment]
@chuckcarpenter did you get a chance to work on this? I'm not savvy enough with svelte or this lib's internals to give it a crack myself but your help would be appreciated 🙏🏼 

We're also using shepard in a slightly contrived use case, with iframes in the mix - so a clean solution would be much preferred. Stuck on next 12 till then.

**Comment by chuckcarpenter** [comment]
@amitav13 I haven't had time for this issue, but have you tried just using Shepherd 11 directly?

**Comment by amitav13** [comment]
> @amitav13 I haven't had time for this issue, but have you tried just using Shepherd 11 directly?

No I haven't. That'd require a decent amount of rework in our case though, not sure if we'd be able to re-implement it with vanilla shepard.
