### ISSUE TITLE
TypeError: tour.addStep is not a function

### ISSUE THREAD

**Issue by erictet** [shipshapecode/react-shepherd#692]
Hi,
I've tried implementing the simple example provided in the docs, but I'm getting the error below. I've also tried using the plain JS version of Shepherd, and I'm getting the same error.
Cheers,
Eric.

React Wrapper error:
![image](https://user-images.githubusercontent.com/56214415/218347202-784f438d-0996-4971-9d9e-7d9bceea70b4.png)

PlainJS error:
![image](https://user-images.githubusercontent.com/56214415/218347050-77978084-37b3-485b-a477-3872faf5eea2.png)
![image](https://user-images.githubusercontent.com/56214415/218347078-4d36f799-29f3-4ec4-90da-ef584e676d25.png)

My code is below:
```
import { ShepherdTour, ShepherdTourContext } from 'react-shepherd';

const tourOptions = {
    defaultStepOptions: {
        cancelIcon: {
            enabled: true
        }
    },
    useModalOverlay: true
};
const steps = [
    {
        id: 'intro',
        attachTo: { element: '.first-element', on: 'bottom' },
        beforeShowPromise: function () {
            return new Promise(function (resolve) {
                setTimeout(function () {
                    window.scrollTo(0, 0);
                    resolve();
                }, 500);
            });
        },
        buttons: [
            {
                classes: 'shepherd-button-secondary',
                text: 'Exit',
                type: 'cancel'
            },
            {
                classes: 'shepherd-button-primary',
                text: 'Back',
                type: 'back'
            },
            {
                classes: 'shepherd-button-primary',
                text: 'Next',
                type: 'next'
            }
        ],
        classes: 'custom-class-name-1 custom-class-name-2',
        highlightClass: 'highlight',
        scrollTo: false,
        cancelIcon: {
            enabled: true,
        },
        title: 'Welcome to React-Shepherd!',
        text: ['React-Shepherd is a JavaScript library for guiding users through your React app.'],
        when: {
            show: () => {
                console.log('show step');
            },
            hide: () => {
                console.log('hide step');
            }
        }
    },
];

function StartShepherdButton() {
    const tour = useContext(ShepherdTourContext);

    return (
        <button className="button dark" onClick={tour.start}>
            Start Tour
        </button>
    );
}
```

```
<ShepherdTour steps={steps} tourOptions={tourOptions}>
    <StartShepherdButton />
</ShepherdTour>
```

**Comment by chuckcarpenter** [comment]
@erictet not able to replicate at this time, but am planning to convert the example site to Astro and so it'll remove the Next portion to simplify things. e.g., https://codesandbox.io/p/sandbox/crazy-oskar-4xiug

I'll post here if I have issues or not.

**Comment by gersanco** [comment]
@erictet I was having the same issue, in my case I solved it try this:
`
const stepsToTour=[]

useEffect(() => {
  steps.map((step) => stepsToTour.push(step))
},[])

<ShepherdTour steps={stepsToTour} tourOptions={tourOptions}>
    <StartShepherdButton />
</ShepherdTour>
`

The problem that I had was during the first render. Ones that the component is mounted it works.

**Comment by chuckcarpenter** [comment]
That makes sense. In the Next.js example I use dynamic import to make sure we have Window and the DOM.

**Comment by dcselek-setsis** [comment]
> @erictet I was having the same issue, in my case I solved it try this:
> 
> ```js
> const stepsToTour=[]
> 
> useEffect(() => {
>   steps.map((step) => stepsToTour.push(step))
> },[])
> 
> <ShepherdTour steps={stepsToTour} tourOptions={tourOptions}>
>     <StartShepherdButton />
> </ShepherdTour>
> ```
> 
> The problem that I had was during the first render. Ones that the component is mounted it works.

Thank you for solution
