### ISSUE TITLE
Home page has "overflow:hidden" on body/html

### ISSUE THREAD

**Issue by impressivewebs** [shipshapecode/react-shepherd#717]
The home page is unscrollable due to "overflow: hidden":

https://shipshape-react-shepherd.netlify.app/

Is this by design? There's no way to scroll down the page other than to trigger the tour.

**Comment by dangkhoipro** [comment]
I think this is the cause. Maybe they make some mistake, because I try to remove `overflow: hidden` and the page still works perfectly fine.
<img width="613" alt="image" src="https://github.com/shipshapecode/react-shepherd/assets/26812593/cf1ea374-a4bc-41d2-be04-577a0ee9ad59">

**Comment by chuckcarpenter** [comment]
@impressivewebs any chance you'd be up for a PR to fix?

**Comment by impressivewebs** [comment]
@chuckcarpenter No problem, done.

**Comment by chuckcarpenter** [comment]
converted to Astro, no longer an issue.
