### ISSUE TITLE
Archive this package?

### ISSUE THREAD

**Issue by chuckcarpenter** [shipshapecode/react-shepherd#735]
### Discussed in https://github.com/shipshapecode/react-shepherd/discussions/731

<div type='discussions-op-text'>

<sup>Originally posted by **chuckcarpenter** August 11, 2023</sup>
## 👋 Outreach to users about this package
 We've been discussing whether this package is really even needed, based on some opinions in it and changes that have occurred in React/Next.
  * This package was first created during React class components, so considered those lifecycle methods.
  * The addition of Context added some helpers to track some level of universal state.
  * Refactored to use hooks with context.
  * Adds some opinions to the base Shepherd.js library that might not be best for all users.

 The thoughts are to instead archive this package and add the previous/current iterations more as a recipe on the main Shepherd [docs](https://shepherdjs.dev/docs) site. We'd love to get feedback from the community of users on that.
</div>

**Comment by kenzaflow** [comment]
I made quite a bit of progress implementing the dependency until I came to this:

```jsx

// inside a step:

buttons: [
  {
    text: 'Start',
    action: () => {
      const menuButton =
	      document.querySelector<HTMLButtonElement>('[data-tour="step-2"]')
      if (menuButton) {
	      menuButton.click()
            // cannot access this (obviously) or context!!!!!
            // for tour.next() or something
            // can be fixed by adding an instance in the action props
            // like action: (tour) => ...
      }
    },
    type: 'next',
  },
],
```

Only fires `type` in this case.

In the docs, in Step > button.action says:

"A function executed when (...) so things like **this.next** will work inside the action."

F***

**Comment by chuckcarpenter** [comment]
@kenzaflow if you provide a type, then that's the default. e.g., https://github.com/shipshapecode/react-shepherd/blob/master/packages/lib/src/index.tsx#L45

This confusion though is another reason we've been considering deprecating this package.

**Comment by kenzaflow** [comment]
Why not use both like type: "action-next" or "action-next-reverse

**Comment by chuckcarpenter** [comment]
@kenzaflow the docs for Shepherd assume a global scope. In react, you can have the scope of the steps setup have access to things like context. 

```
import React, { Component, useContext } from 'react'
import { ShepherdTour, ShepherdTourContext } from 'react-shepherd'
import newSteps from './steps'

const tourOptions = {
  defaultStepOptions: {
    cancelIcon: {
      enabled: true
    }
  },
  useModalOverlay: true
};

function Button() {
  const tour = useContext(ShepherdTourContext);
  tour.steps[0].options.buttons.push({
    text: 'Next',
    action() {
      console.log('you did a thing');
      tour.next();
    }
  });

  return (
    <button className="button dark" onClick={tour.start}>
      Start Tour
    </button>
  );
}

class App extends Component {
  render() {
    return (
      <div>
        <ShepherdTour steps={newSteps} tourOptions={tourOptions}>
          <Button />
        </ShepherdTour>
      </div>
    );
  }
}
```

I'm not saying that's the most elegant option, but it's pretty flexible and doesn't require any changes to the library to make that work.

**Comment by kenzaflow** [comment]
That's ok, works.. Thank you, I don't use this library anymore, I created the "tour" in the org's app from scratch

**Comment by chuckcarpenter** [comment]
@kenzaflow I actually think that's the way to go, using Shepherdjs directly and why this issue is open. A recipe in those docs makes more sense to me.
