### ISSUE TITLE
How to use the shephourd tour in a SPA

### ISSUE THREAD

**Issue by Baspa** [shipshapecode/react-shepherd#82]
I want to switch between different pages during the tour. For example, when a user completes the first step, it moves to the second step on another page. How can I implement this? Are there any examples available?

**Comment by Baspa** [comment]
I tried adding an action function to the button and in there linking to the other page, after that show step two but after the `window.location.replace` all the 'step-data' is lost.  

```
    buttons: [
      {
        classes: 'shepherd-button-primary',
        text: 'Next',
        type: 'next',
        action() {
          window.location.replace("/meeting-types");
          return this.show('twee');
        }
      }
```

**Comment by rwwagner90** [comment]
@Baspa this is definitely possible. You would need to start the tour on the first page, wait for the second page to show, then show the next step.
